sudo: required
dist: trusty
language: cpp

os:
  - linux

compiler: 
  - gcc

language: cpp
notifications:
  email:
    - chenzongzhi@360.cn

script:
  - make -C slash
  - make -C slash example
  - make -C slash check
